import { CareerHub } from "./types";

export const careerHubs: CareerHub[] = [
  {
    id: "singapore",
    city: "Singapore",
    country: "Singapore",
    region: "Southeast Asia",
    coordinates: [103.8198, 1.3521],
    hubType: "AI & FinTech Hub",
    tagline:
      "Asia-Pacific's gateway for product, data, and regional HQ roles.",
    industries: [
      "Technology",
      "Finance",
      "Consulting",
      "E-commerce",
      "Climate Tech",
    ],
    demandSkills: [
      "Python",
      "SQL",
      "React",
      "Machine Learning",
      "Product Management",
      "Data Visualization",
      "Agile",
      "AWS",
    ],
    suitableRoles: [
      "Product Manager",
      "Data Analyst",
      "Software Engineer",
      "Business Analyst",
      "Growth Strategist",
    ],
    salaryRange: { min: 55000, max: 120000, currency: "SGD" },
    workModes: ["Hybrid", "On-site"],
    mobilityDifficulty: "Low",
    costOfLiving: "Very High",
    opportunities: [
      { title: "Associate Product Manager", type: "job", organization: "Grab" },
      {
        title: "Data Analytics Intern",
        type: "internship",
        organization: "Shopee",
      },
      {
        title: "FinTech Accelerator Program",
        type: "course",
        organization: "MAS FinTech Festival",
      },
      {
        title: "Climate Data Fellow",
        type: "internship",
        organization: "Temasek Foundation",
      },
    ],
    recommendedActions: [
      "Apply to Grab or Shopee APM programs",
      "Attend Singapore FinTech Festival for networking",
      "Complete Google Data Analytics Professional Certificate",
    ],
    pathwayTags: ["Stable Growth", "High Salary"],
  },
  {
    id: "kuala-lumpur",
    city: "Kuala Lumpur",
    country: "Malaysia",
    region: "Southeast Asia",
    coordinates: [101.6869, 3.139],
    hubType: "Shared Services & Semiconductor Hub",
    tagline:
      "Affordable launchpad for analytics, consulting, and semiconductor careers.",
    industries: [
      "Technology",
      "Consulting",
      "Manufacturing",
      "Finance",
      "Energy",
    ],
    demandSkills: [
      "Python",
      "SQL",
      "Excel",
      "Tableau",
      "Data Visualization",
      "Project Management",
      "Research",
      "Agile",
    ],
    suitableRoles: [
      "Data Analyst",
      "Business Consultant",
      "Process Engineer",
      "Research Analyst",
      "Project Coordinator",
    ],
    salaryRange: { min: 36000, max: 84000, currency: "MYR" },
    workModes: ["Hybrid", "On-site"],
    mobilityDifficulty: "Low",
    costOfLiving: "Low",
    opportunities: [
      {
        title: "Graduate Analyst",
        type: "job",
        organization: "Accenture Malaysia",
      },
      {
        title: "Data Intern",
        type: "internship",
        organization: "Intel Penang",
      },
      {
        title: "Consulting Case Workshop",
        type: "course",
        organization: "McKinsey Academy",
      },
      {
        title: "ESG Reporting Analyst",
        type: "job",
        organization: "PETRONAS",
      },
    ],
    recommendedActions: [
      "Target shared services centres (Accenture, Deloitte, EY)",
      "Build a Tableau portfolio showcasing ESG dashboards",
      "Network at Malaysia Tech Week events",
    ],
    pathwayTags: ["Stable Growth", "Skill Pivot"],
  },
  {
    id: "jakarta",
    city: "Jakarta",
    country: "Indonesia",
    region: "Southeast Asia",
    coordinates: [106.8456, -6.2088],
    hubType: "Startup & Digital Economy Hub",
    tagline:
      "Southeast Asia's largest digital economy with booming startup ecosystem.",
    industries: ["Technology", "E-commerce", "Finance", "Education", "Media"],
    demandSkills: [
      "JavaScript",
      "React",
      "Python",
      "SQL",
      "Product Management",
      "Data Visualization",
      "Communication",
      "Agile",
    ],
    suitableRoles: [
      "Product Manager",
      "Full-Stack Developer",
      "Growth Analyst",
      "UX Researcher",
      "Content Strategist",
    ],
    salaryRange: { min: 120000000, max: 360000000, currency: "IDR" },
    workModes: ["Hybrid", "On-site", "Remote"],
    mobilityDifficulty: "Medium",
    costOfLiving: "Low",
    opportunities: [
      {
        title: "Product Analyst",
        type: "job",
        organization: "GoTo Group",
      },
      {
        title: "Data Science Intern",
        type: "internship",
        organization: "Tokopedia",
      },
      {
        title: "Startup Bootcamp",
        type: "course",
        organization: "Endeavor Indonesia",
      },
    ],
    recommendedActions: [
      "Connect with GoTo Group or Bukalapak recruiters on LinkedIn",
      "Learn Bahasa Indonesia basics for cultural fit",
      "Attend Jakarta Tech Meetups for ecosystem exposure",
    ],
    pathwayTags: ["Startup / Builder", "Skill Pivot"],
  },
  {
    id: "bangkok",
    city: "Bangkok",
    country: "Thailand",
    region: "Southeast Asia",
    coordinates: [100.5018, 13.7563],
    hubType: "Digital & Creative Economy Hub",
    tagline:
      "Emerging tech scene with growing demand for digital and creative talent.",
    industries: ["Technology", "Media", "E-commerce", "Healthcare", "Retail"],
    demandSkills: [
      "Python",
      "JavaScript",
      "Figma",
      "Data Visualization",
      "Communication",
      "Project Management",
      "Writing",
      "Excel",
    ],
    suitableRoles: [
      "Digital Marketing Analyst",
      "UX Designer",
      "Data Analyst",
      "Product Coordinator",
      "Content Manager",
    ],
    salaryRange: { min: 600000, max: 1800000, currency: "THB" },
    workModes: ["Hybrid", "On-site"],
    mobilityDifficulty: "Medium",
    costOfLiving: "Low",
    opportunities: [
      {
        title: "Digital Analyst",
        type: "job",
        organization: "Agoda",
      },
      {
        title: "UX Research Intern",
        type: "internship",
        organization: "LINE Thailand",
      },
      {
        title: "SEA Digital Summit",
        type: "course",
        organization: "TechSauce",
      },
    ],
    recommendedActions: [
      "Apply to Agoda's analytics team for regional exposure",
      "Attend TechSauce Global Summit for networking",
      "Build a UX case study with a Thai market focus",
    ],
    pathwayTags: ["Stable Growth", "Skill Pivot"],
  },
  {
    id: "tokyo",
    city: "Tokyo",
    country: "Japan",
    region: "East Asia",
    coordinates: [139.6917, 35.6895],
    hubType: "Robotics & Advanced Manufacturing Hub",
    tagline:
      "World leader in robotics, gaming, and embedded systems innovation.",
    industries: [
      "Technology",
      "Manufacturing",
      "Gaming",
      "Healthcare",
      "Energy",
    ],
    demandSkills: [
      "Python",
      "C++",
      "Machine Learning",
      "Data Visualization",
      "Research",
      "Project Management",
      "Git",
      "Docker",
    ],
    suitableRoles: [
      "ML Engineer",
      "Robotics Software Developer",
      "Data Scientist",
      "Research Engineer",
      "Product Manager (Tech)",
    ],
    salaryRange: { min: 5000000, max: 12000000, currency: "JPY" },
    workModes: ["On-site", "Hybrid"],
    mobilityDifficulty: "High",
    costOfLiving: "High",
    opportunities: [
      {
        title: "AI Research Intern",
        type: "internship",
        organization: "Sony AI",
      },
      {
        title: "Data Engineer",
        type: "job",
        organization: "Mercari",
      },
      {
        title: "Japanese Language & Tech Program",
        type: "course",
        organization: "MEXT Scholarship",
      },
    ],
    recommendedActions: [
      "Begin JLPT N3 Japanese language preparation",
      "Apply to MEXT scholarship for graduate research",
      "Build a robotics or ML portfolio project on GitHub",
    ],
    pathwayTags: ["High Salary", "Leadership"],
  },
  {
    id: "seoul",
    city: "Seoul",
    country: "South Korea",
    region: "East Asia",
    coordinates: [126.978, 37.5665],
    hubType: "Consumer Tech & AI Hub",
    tagline:
      "Global leader in consumer electronics, entertainment tech, and AI.",
    industries: [
      "Technology",
      "Media",
      "Manufacturing",
      "Finance",
      "Healthcare",
    ],
    demandSkills: [
      "Python",
      "Machine Learning",
      "TypeScript",
      "React",
      "Data Visualization",
      "Research",
      "Git",
      "AWS",
    ],
    suitableRoles: [
      "AI Engineer",
      "Data Scientist",
      "Product Designer",
      "Software Engineer",
      "UX Researcher",
    ],
    salaryRange: { min: 40000000, max: 90000000, currency: "KRW" },
    workModes: ["On-site", "Hybrid"],
    mobilityDifficulty: "High",
    costOfLiving: "High",
    opportunities: [
      {
        title: "AI Research Associate",
        type: "job",
        organization: "Samsung Research",
      },
      {
        title: "Product Design Intern",
        type: "internship",
        organization: "Naver",
      },
      {
        title: "K-Startup Grand Challenge",
        type: "challenge",
        organization: "Korean Government",
      },
    ],
    recommendedActions: [
      "Apply to Samsung Global Internship Program",
      "Enter K-Startup Grand Challenge for visa sponsorship",
      "Study TOPIK Korean proficiency for career advantage",
    ],
    pathwayTags: ["High Salary", "Startup / Builder"],
  },
  {
    id: "dubai",
    city: "Dubai",
    country: "UAE",
    region: "Middle East",
    coordinates: [55.2708, 25.2048],
    hubType: "Smart Cities & Sustainability Hub",
    tagline:
      "Rapidly growing hub for smart cities, sustainability, and global logistics.",
    industries: [
      "Energy",
      "Finance",
      "Technology",
      "Climate Tech",
      "Consulting",
    ],
    demandSkills: [
      "Python",
      "Excel",
      "Tableau",
      "Project Management",
      "Data Visualization",
      "Public Speaking",
      "Research",
      "SQL",
    ],
    suitableRoles: [
      "Sustainability Analyst",
      "Management Consultant",
      "Data Analyst",
      "Smart City Project Manager",
      "ESG Advisor",
    ],
    salaryRange: { min: 180000, max: 420000, currency: "AED" },
    workModes: ["On-site", "Hybrid"],
    mobilityDifficulty: "Medium",
    costOfLiving: "High",
    opportunities: [
      {
        title: "Sustainability Analyst",
        type: "job",
        organization: "Masdar",
      },
      {
        title: "Strategy Intern",
        type: "internship",
        organization: "McKinsey Dubai",
      },
      {
        title: "Smart City Innovation Challenge",
        type: "challenge",
        organization: "Dubai Future Foundation",
      },
    ],
    recommendedActions: [
      "Apply to Masdar or DEWA sustainability programs",
      "Attend GITEX Global for tech networking in the Gulf",
      "Complete a sustainability or ESG certification",
    ],
    pathwayTags: ["High Salary", "Leadership"],
  },
  {
    id: "london",
    city: "London",
    country: "United Kingdom",
    region: "Europe",
    coordinates: [-0.1276, 51.5074],
    hubType: "Consulting & Climate Tech Hub",
    tagline:
      "Global centre for consulting, finance, policy, and climate technology.",
    industries: [
      "Finance",
      "Consulting",
      "Climate Tech",
      "Technology",
      "Government",
    ],
    demandSkills: [
      "Python",
      "SQL",
      "Excel",
      "Public Speaking",
      "Research",
      "Data Visualization",
      "Project Management",
      "Writing",
    ],
    suitableRoles: [
      "Management Consultant",
      "Climate Policy Analyst",
      "Data Analyst",
      "Product Manager",
      "Sustainability Strategist",
    ],
    salaryRange: { min: 35000, max: 85000, currency: "GBP" },
    workModes: ["Hybrid", "On-site", "Remote"],
    mobilityDifficulty: "Medium",
    costOfLiving: "Very High",
    opportunities: [
      {
        title: "Graduate Consultant",
        type: "job",
        organization: "BCG London",
      },
      {
        title: "Climate Data Analyst",
        type: "job",
        organization: "Carbon Trust",
      },
      {
        title: "Policy & Sustainability Fellowship",
        type: "internship",
        organization: "Chatham House",
      },
      {
        title: "London Climate Action Week",
        type: "course",
        organization: "Climate Action",
      },
    ],
    recommendedActions: [
      "Target graduate consulting programs (BCG, Bain, McKinsey)",
      "Apply to UK Global Talent Visa (Tech Nation pathway)",
      "Build climate policy writing samples for your portfolio",
    ],
    pathwayTags: ["Stable Growth", "Leadership"],
  },
  {
    id: "berlin",
    city: "Berlin",
    country: "Germany",
    region: "Europe",
    coordinates: [13.405, 52.52],
    hubType: "Climate Tech & Startup Hub",
    tagline:
      "Europe's startup capital with a thriving climate tech ecosystem.",
    industries: [
      "Climate Tech",
      "Technology",
      "Social Enterprise",
      "E-commerce",
      "Energy",
    ],
    demandSkills: [
      "Python",
      "JavaScript",
      "TypeScript",
      "React",
      "Git",
      "Docker",
      "Agile",
      "Data Visualization",
    ],
    suitableRoles: [
      "Climate Tech Product Manager",
      "Full-Stack Developer",
      "Sustainability Data Analyst",
      "Impact Strategist",
      "Growth Engineer",
    ],
    salaryRange: { min: 45000, max: 90000, currency: "EUR" },
    workModes: ["Remote", "Hybrid"],
    mobilityDifficulty: "Medium",
    costOfLiving: "Medium",
    opportunities: [
      {
        title: "Climate Product Manager",
        type: "job",
        organization: "Ecosia",
      },
      {
        title: "Impact Analyst Intern",
        type: "internship",
        organization: "Climate-KIC",
      },
      {
        title: "Berlin Climate Startup Bootcamp",
        type: "course",
        organization: "Green Startups Incubator",
      },
    ],
    recommendedActions: [
      "Apply to Ecosia, Thermondo, or 1KOMMA5 for climate roles",
      "Attend Berlin Climate Week for ecosystem networking",
      "Apply for EU Blue Card work visa pathway",
    ],
    pathwayTags: ["Startup / Builder", "Skill Pivot"],
  },
  {
    id: "amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    region: "Europe",
    coordinates: [4.9041, 52.3676],
    hubType: "Product & Sustainability Hub",
    tagline:
      "Innovation-driven city strong in product, sustainability, and design.",
    industries: [
      "Technology",
      "Climate Tech",
      "E-commerce",
      "Finance",
      "Social Enterprise",
    ],
    demandSkills: [
      "Python",
      "SQL",
      "Figma",
      "React",
      "Data Visualization",
      "Product Management",
      "Agile",
      "Communication",
    ],
    suitableRoles: [
      "Product Manager",
      "UX Researcher",
      "Data Analyst",
      "Sustainability Consultant",
      "Growth Marketer",
    ],
    salaryRange: { min: 40000, max: 85000, currency: "EUR" },
    workModes: ["Hybrid", "Remote"],
    mobilityDifficulty: "Medium",
    costOfLiving: "High",
    opportunities: [
      {
        title: "Product Analyst",
        type: "job",
        organization: "Booking.com",
      },
      {
        title: "Sustainability Data Intern",
        type: "internship",
        organization: "Fairphone",
      },
      {
        title: "Amsterdam Impact Fellowship",
        type: "course",
        organization: "Amsterdam Impact",
      },
    ],
    recommendedActions: [
      "Apply to Booking.com, Adyen, or Mollie for product roles",
      "Explore Dutch Orientation Visa for job searching",
      "Join Amsterdam Sustainability Meetup community",
    ],
    pathwayTags: ["Stable Growth", "Skill Pivot"],
  },
  {
    id: "toronto",
    city: "Toronto",
    country: "Canada",
    region: "North America",
    coordinates: [-79.3832, 43.6532],
    hubType: "AI & Cloud Computing Hub",
    tagline:
      "North America's rising AI corridor with strong research ecosystem.",
    industries: [
      "Technology",
      "Finance",
      "Healthcare",
      "Education",
      "Consulting",
    ],
    demandSkills: [
      "Python",
      "Machine Learning",
      "SQL",
      "AWS",
      "Docker",
      "TypeScript",
      "Git",
      "Research",
    ],
    suitableRoles: [
      "ML Engineer",
      "Data Scientist",
      "Cloud Engineer",
      "Research Analyst",
      "Product Manager",
    ],
    salaryRange: { min: 65000, max: 140000, currency: "CAD" },
    workModes: ["Hybrid", "Remote"],
    mobilityDifficulty: "Medium",
    costOfLiving: "High",
    opportunities: [
      {
        title: "ML Research Associate",
        type: "job",
        organization: "Vector Institute",
      },
      {
        title: "Data Science Intern",
        type: "internship",
        organization: "Shopify",
      },
      {
        title: "AI Ethics & Safety Program",
        type: "course",
        organization: "Mila Quebec",
      },
    ],
    recommendedActions: [
      "Apply to Vector Institute or Shopify internships",
      "Explore Express Entry immigration pathway for Canada",
      "Contribute to open-source ML projects for visibility",
    ],
    pathwayTags: ["High Salary", "Leadership"],
  },
  {
    id: "new-york",
    city: "New York",
    country: "United States",
    region: "North America",
    coordinates: [-74.006, 40.7128],
    hubType: "Finance & Media Tech Hub",
    tagline:
      "Global capital of finance, media, and data-driven product roles.",
    industries: ["Finance", "Media", "Technology", "Consulting", "Healthcare"],
    demandSkills: [
      "Python",
      "SQL",
      "Excel",
      "Data Visualization",
      "Public Speaking",
      "Research",
      "Tableau",
      "Communication",
    ],
    suitableRoles: [
      "Financial Analyst",
      "Data Analyst",
      "Product Manager",
      "Strategy Consultant",
      "Media Analyst",
    ],
    salaryRange: { min: 70000, max: 160000, currency: "USD" },
    workModes: ["Hybrid", "On-site"],
    mobilityDifficulty: "High",
    costOfLiving: "Very High",
    opportunities: [
      {
        title: "Product Analyst",
        type: "job",
        organization: "Bloomberg",
      },
      {
        title: "Data Science Fellow",
        type: "internship",
        organization: "The New York Times",
      },
      {
        title: "FinTech Innovation Lab",
        type: "course",
        organization: "Accenture",
      },
    ],
    recommendedActions: [
      "Apply for OPT/H-1B sponsor roles at major firms",
      "Build finance-oriented data visualization portfolio",
      "Network via NYC Data Science & PM meetup groups",
    ],
    pathwayTags: ["High Salary", "Stable Growth"],
  },
  {
    id: "san-francisco",
    city: "San Francisco",
    country: "United States",
    region: "North America",
    coordinates: [-122.4194, 37.7749],
    hubType: "AI & Venture-Backed Startup Hub",
    tagline: "The epicentre of AI innovation, startups, and venture capital.",
    industries: [
      "Technology",
      "Climate Tech",
      "Finance",
      "Healthcare",
      "E-commerce",
    ],
    demandSkills: [
      "Python",
      "Machine Learning",
      "TypeScript",
      "React",
      "AWS",
      "Docker",
      "Git",
      "Agile",
    ],
    suitableRoles: [
      "AI Engineer",
      "Startup Product Manager",
      "Full-Stack Engineer",
      "Data Scientist",
      "Growth Lead",
    ],
    salaryRange: { min: 90000, max: 200000, currency: "USD" },
    workModes: ["Remote", "Hybrid", "On-site"],
    mobilityDifficulty: "High",
    costOfLiving: "Very High",
    opportunities: [
      {
        title: "AI Product Manager",
        type: "job",
        organization: "Anthropic",
      },
      {
        title: "ML Engineer Intern",
        type: "internship",
        organization: "OpenAI",
      },
      {
        title: "Y Combinator Startup School",
        type: "course",
        organization: "Y Combinator",
      },
    ],
    recommendedActions: [
      "Apply to YC Startup School for founder fundamentals",
      "Target H-1B sponsor companies (Google, Meta, Anthropic)",
      "Build and ship an AI side project to demonstrate skills",
    ],
    pathwayTags: ["Startup / Builder", "High Salary"],
  },
  {
    id: "sydney",
    city: "Sydney",
    country: "Australia",
    region: "Oceania",
    coordinates: [151.2093, -33.8688],
    hubType: "Cloud & Sustainability Hub",
    tagline:
      "Strong in cloud, consulting, and sustainability with great quality of life.",
    industries: [
      "Technology",
      "Consulting",
      "Climate Tech",
      "Finance",
      "Government",
    ],
    demandSkills: [
      "Python",
      "SQL",
      "AWS",
      "Tableau",
      "Data Visualization",
      "Public Speaking",
      "Project Management",
      "Agile",
    ],
    suitableRoles: [
      "Cloud Consultant",
      "Data Analyst",
      "Product Manager",
      "Sustainability Analyst",
      "Business Analyst",
    ],
    salaryRange: { min: 70000, max: 140000, currency: "AUD" },
    workModes: ["Hybrid", "Remote"],
    mobilityDifficulty: "Low",
    costOfLiving: "Very High",
    opportunities: [
      {
        title: "Associate Product Manager",
        type: "job",
        organization: "Canva",
      },
      {
        title: "Data Analyst Intern",
        type: "internship",
        organization: "Atlassian",
      },
      {
        title: "Climate Analytics Fellow",
        type: "internship",
        organization: "Climateworks Centre",
      },
      {
        title: "AWS Cloud Practitioner",
        type: "course",
        organization: "Amazon Web Services",
      },
    ],
    recommendedActions: [
      "Apply to Canva or Atlassian graduate programs",
      "Target subclass 485 post-study work visa pathway",
      "Complete AWS Cloud Practitioner certification",
    ],
    pathwayTags: ["Stable Growth", "Leadership"],
  },
];
