import { MentorCard } from "./types";

export const mockMentors: MentorCard[] = [
  {
    id: "mentor-1",
    name: "Sarah Chen",
    role: "Senior Product Manager",
    company: "Stripe",
    industry: "FinTech",
    location: "Singapore",
    expertise: ["Product Strategy", "Data Analytics", "Career Pivoting", "Agile"],
    bio: "Transitioned from data analytics to product management. Now leads payments product at Stripe APAC. Passionate about helping early-career professionals find their direction.",
    imageInitials: "SC",
    suggestedQuestions: [
      "How did you transition from analytics to product management?",
      "What skills were most important for your PM interviews?",
      "How do you use your data background in your PM role?",
      "What's one thing you wish you knew before starting your career?",
    ],
    pathwayTags: ["skill-pivot", "high-salary", "stable-growth"],
  },
  {
    id: "mentor-2",
    name: "James Okafor",
    role: "Founder & CEO",
    company: "CarbonLedger",
    industry: "Climate Tech",
    location: "Melbourne",
    expertise: ["Climate Technology", "Entrepreneurship", "Impact Measurement", "Fundraising"],
    bio: "Built a carbon accounting platform serving 200+ companies. Previously sustainability consultant at BCG. Believes every career can include purpose.",
    imageInitials: "JO",
    suggestedQuestions: [
      "What does a typical day look like as a climate-tech founder?",
      "How important is technical skill vs domain knowledge in this space?",
      "What resources would you recommend for someone entering climate tech?",
      "How did you make the leap from consulting to starting your own company?",
    ],
    pathwayTags: ["startup-builder", "skill-pivot"],
  },
  {
    id: "mentor-3",
    name: "Priya Sharma",
    role: "Data Science Lead",
    company: "Grab",
    industry: "Technology",
    location: "Singapore",
    expertise: ["Machine Learning", "Python", "Data Visualization", "SQL", "Mentoring"],
    bio: "Leads a team of 12 data scientists at Grab. Started as a junior analyst and grew through continuous learning. Mentors 5+ early-career data professionals each year.",
    imageInitials: "PS",
    suggestedQuestions: [
      "What's the most important skill for a junior data scientist?",
      "How did you grow from analyst to lead in 5 years?",
      "What projects should I build to stand out in data science applications?",
      "How do you stay current with ML developments?",
    ],
    pathwayTags: ["stable-growth", "high-salary"],
  },
  {
    id: "mentor-4",
    name: "Marcus Webb",
    role: "UX Design Director",
    company: "Canva",
    industry: "Technology",
    location: "Sydney",
    expertise: ["UX Design", "Design Thinking", "Leadership", "User Research"],
    bio: "Leads product design for Canva's enterprise suite. Built UX teams from scratch at two startups before joining Canva. Strong believer in T-shaped design careers.",
    imageInitials: "MW",
    suggestedQuestions: [
      "How do you build a compelling UX portfolio as a fresh graduate?",
      "What's the difference between UX at a startup vs a large company?",
      "How did you transition into a leadership role in design?",
      "What tools and processes does your team use?",
    ],
    pathwayTags: ["stable-growth", "leadership"],
  },
  {
    id: "mentor-5",
    name: "Rina Tanaka",
    role: "Management Consultant",
    company: "McKinsey & Company",
    industry: "Consulting",
    location: "Tokyo",
    expertise: ["Consulting", "Strategy", "Problem Solving", "Communication", "Project Management"],
    bio: "Associate Partner at McKinsey Tokyo office. Specializes in digital transformation for manufacturing clients. Graduated from a non-target university and broke into consulting.",
    imageInitials: "RT",
    suggestedQuestions: [
      "How did you break into consulting from a non-target school?",
      "What skills matter most in management consulting?",
      "What's the work-life balance really like in consulting?",
      "How should I prepare for case interviews?",
    ],
    pathwayTags: ["high-salary", "leadership", "stable-growth"],
  },
  {
    id: "mentor-6",
    name: "Ahmed Al-Rashid",
    role: "VP of Engineering",
    company: "Careem",
    industry: "Technology",
    location: "Dubai",
    expertise: ["Software Engineering", "System Design", "Leadership", "Scaling Teams"],
    bio: "VP of Engineering at Careem (Super App). Built and scaled engineering teams from 10 to 80. Passionate about developing engineering leaders in emerging tech markets.",
    imageInitials: "AR",
    suggestedQuestions: [
      "What does the path from junior engineer to VP look like?",
      "How do you evaluate candidates for engineering roles?",
      "What's the tech scene like in the Middle East?",
      "How do you balance technical depth with management responsibilities?",
    ],
    pathwayTags: ["leadership", "high-salary", "stable-growth"],
  },
  {
    id: "mentor-7",
    name: "Lisa Nguyen",
    role: "Growth Product Manager",
    company: "Shopee",
    industry: "E-commerce",
    location: "Ho Chi Minh City",
    expertise: ["Growth Strategy", "Product Management", "A/B Testing", "SQL", "Marketing"],
    bio: "Leads growth experiments at Shopee Vietnam. Previously in marketing before pivoting to product. Loves helping career changers find their way into tech.",
    imageInitials: "LN",
    suggestedQuestions: [
      "How did you pivot from marketing to product management?",
      "What growth frameworks do you use daily?",
      "How important is technical skill for a growth PM?",
      "What's the e-commerce industry like in Southeast Asia?",
    ],
    pathwayTags: ["skill-pivot", "stable-growth"],
  },
  {
    id: "mentor-8",
    name: "Daniel Kim",
    role: "Co-Founder",
    company: "EduVerse",
    industry: "Education",
    location: "Seoul",
    expertise: ["Entrepreneurship", "EdTech", "Full-Stack Development", "Fundraising"],
    bio: "Co-founded an EdTech startup building AI-powered learning tools. Previously software engineer at Samsung. Dropped out of a stable career to chase his passion for education.",
    imageInitials: "DK",
    suggestedQuestions: [
      "How do you decide when to leave a stable job for a startup?",
      "What's the most important thing for a first-time founder?",
      "How did you validate your EdTech idea before building?",
      "What technical skills are most valuable for a technical co-founder?",
    ],
    pathwayTags: ["startup-builder", "skill-pivot"],
  },
  {
    id: "mentor-9",
    name: "Emma van den Berg",
    role: "Sustainability Analyst",
    company: "Unilever",
    industry: "Climate Tech",
    location: "Amsterdam",
    expertise: ["Sustainability", "Data Analytics", "ESG Reporting", "Research"],
    bio: "Leads ESG analytics at Unilever Europe. Combines environmental science background with data skills to drive corporate sustainability initiatives.",
    imageInitials: "EB",
    suggestedQuestions: [
      "How do you combine data analytics with sustainability?",
      "What certifications matter for ESG and sustainability roles?",
      "What's the career trajectory in corporate sustainability?",
      "How can someone without an environmental background break in?",
    ],
    pathwayTags: ["stable-growth", "skill-pivot"],
  },
  {
    id: "mentor-10",
    name: "Michael Torres",
    role: "Engineering Manager",
    company: "Atlassian",
    industry: "Technology",
    location: "Sydney",
    expertise: ["Software Engineering", "Agile", "Team Building", "React", "TypeScript"],
    bio: "Engineering Manager at Atlassian leading cloud infrastructure tools. Started as an intern and worked his way up over 8 years. Active in the Sydney tech community.",
    imageInitials: "MT",
    suggestedQuestions: [
      "What helped you stand out as an intern and get a return offer?",
      "How do you balance coding with management responsibilities?",
      "What makes a strong software engineering portfolio?",
      "How important are side projects in getting hired?",
    ],
    pathwayTags: ["stable-growth", "leadership"],
  },
];
