import { CourseRecommendation } from "./types";

export const mockCourseRecommendations: CourseRecommendation[] = [
  // ── Courses ──
  {
    id: "rec-1",
    title: "Google Data Analytics Professional Certificate",
    type: "certification",
    provider: "Google via Coursera",
    duration: "6 months (self-paced)",
    cost: "$49/mo",
    url: "https://www.coursera.org/professional-certificates/google-data-analytics",
    skillGapsClosed: ["Statistical Analysis", "Advanced SQL", "Data Pipeline Design"],
    whyItMatters: "Industry-recognized credential that validates analytical foundations and signals continuous learning to employers.",
    pathwayImprovement: "Strengthens your Stable Growth Path by adding a recognized certification and closing key analytical skill gaps.",
    relevantPathways: ["stable-growth", "high-salary"],
    difficulty: "beginner",
  },
  {
    id: "rec-2",
    title: "Machine Learning Specialization",
    type: "course",
    provider: "Stanford via Coursera",
    duration: "3 months",
    cost: "$49/mo",
    url: "https://www.coursera.org/specializations/machine-learning-introduction",
    skillGapsClosed: ["Machine Learning", "ML Fundamentals", "Statistical Analysis"],
    whyItMatters: "Taught by Andrew Ng, this is the gold standard intro to ML. Employers recognize this as serious commitment to learning AI/ML.",
    pathwayImprovement: "Opens doors to data science and AI roles across all pathways, especially High Salary and Skill Pivot paths.",
    relevantPathways: ["high-salary", "skill-pivot", "stable-growth"],
    difficulty: "intermediate",
  },
  {
    id: "rec-3",
    title: "Product Management Fundamentals",
    type: "course",
    provider: "Product School",
    duration: "8 weeks",
    cost: "Free",
    url: "https://productschool.com/free-product-management-course",
    skillGapsClosed: ["Product Thinking", "Stakeholder Management", "User Research"],
    whyItMatters: "Gives you the vocabulary and frameworks to speak like a PM. Essential for anyone considering a product career pivot.",
    pathwayImprovement: "Directly supports Skill Pivot Path and Stable Growth Path by building product management foundations.",
    relevantPathways: ["skill-pivot", "stable-growth"],
    difficulty: "beginner",
  },
  {
    id: "rec-4",
    title: "AWS Cloud Practitioner Certification",
    type: "certification",
    provider: "Amazon Web Services",
    duration: "4-6 weeks",
    cost: "$100 (exam fee)",
    url: "https://aws.amazon.com/certification/certified-cloud-practitioner/",
    skillGapsClosed: ["Cloud Architecture", "System Design", "DevOps Basics"],
    whyItMatters: "Cloud skills are in demand everywhere. This entry-level cert proves you understand modern infrastructure and opens doors to cloud-native roles.",
    pathwayImprovement: "Boosts High Salary Path by adding in-demand cloud credentials. Valuable across Singapore, Sydney, and North American hubs.",
    relevantPathways: ["high-salary", "stable-growth"],
    difficulty: "beginner",
  },
  {
    id: "rec-5",
    title: "Full-Stack Web Development Bootcamp",
    type: "course",
    provider: "The Odin Project",
    url: "https://www.theodinproject.com/",
    duration: "6-9 months",
    cost: "Free",
    skillGapsClosed: ["Full-Stack Development", "System Design", "API Integration"],
    whyItMatters: "Hands-on, project-based curriculum that builds real shipping ability. Proves you can build products end-to-end.",
    pathwayImprovement: "Essential for Startup/Builder Path — founders who can code have a massive advantage in early stages.",
    relevantPathways: ["startup-builder", "skill-pivot"],
    difficulty: "intermediate",
  },

  // ── Portfolio Projects ──
  {
    id: "rec-6",
    title: "Climate Data Dashboard",
    type: "portfolio-project",
    provider: "Self-directed",
    duration: "4-6 weeks",
    cost: "Free",
    skillGapsClosed: ["Full-Stack Development", "Data Visualization", "API Integration"],
    whyItMatters: "Combines technical skills with domain interest, creating a portfolio piece that stands out to both tech and climate employers.",
    pathwayImprovement: "Supports Startup/Builder and Skill Pivot paths by demonstrating domain expertise and shipping ability.",
    relevantPathways: ["startup-builder", "skill-pivot"],
    difficulty: "intermediate",
  },
  {
    id: "rec-7",
    title: "Personal Finance Tracker App",
    type: "portfolio-project",
    provider: "Self-directed",
    duration: "3-4 weeks",
    cost: "Free",
    skillGapsClosed: ["Full-Stack Development", "Product Thinking", "UI/UX Design"],
    whyItMatters: "Shows you can build a user-facing product from scratch. FinTech recruiters love seeing financial domain awareness.",
    pathwayImprovement: "Strengthens High Salary Path by demonstrating FinTech domain knowledge and product sense.",
    relevantPathways: ["high-salary", "startup-builder"],
    difficulty: "intermediate",
  },
  {
    id: "rec-8",
    title: "ML Model Deployment Pipeline",
    type: "portfolio-project",
    provider: "Self-directed",
    duration: "2-3 weeks",
    cost: "Free",
    skillGapsClosed: ["Machine Learning", "Cloud Architecture", "DevOps Basics"],
    whyItMatters: "Most candidates can train models but few can deploy them. This demonstrates production-ready ML skills that employers value highly.",
    pathwayImprovement: "Directly boosts Stable Growth and High Salary paths by proving end-to-end ML capability.",
    relevantPathways: ["stable-growth", "high-salary"],
    difficulty: "advanced",
  },

  // ── Certifications ──
  {
    id: "rec-9",
    title: "Certified Scrum Product Owner (CSPO)",
    type: "certification",
    provider: "Scrum Alliance",
    duration: "2-day workshop",
    cost: "$500-800",
    skillGapsClosed: ["Product Thinking", "Stakeholder Management", "Agile"],
    whyItMatters: "Globally recognized agile certification. Signals you understand product ownership in cross-functional teams.",
    pathwayImprovement: "Strengthens Leadership Path and Stable Growth Path by adding structured project management credential.",
    relevantPathways: ["leadership", "stable-growth", "skill-pivot"],
    difficulty: "beginner",
  },
  {
    id: "rec-10",
    title: "Tableau Desktop Specialist",
    type: "certification",
    provider: "Tableau / Salesforce",
    duration: "2-4 weeks prep",
    cost: "$100 (exam fee)",
    skillGapsClosed: ["Data Visualization", "Business Intelligence", "Statistical Analysis"],
    whyItMatters: "Proves you can turn data into visual stories. Highly valued in consulting, analytics, and business intelligence roles.",
    pathwayImprovement: "Strengthens Stable Growth Path by adding an in-demand analytics visualization credential.",
    relevantPathways: ["stable-growth", "high-salary"],
    difficulty: "beginner",
  },

  // ── Communities ──
  {
    id: "rec-11",
    title: "On Deck Fellowship",
    type: "community",
    provider: "On Deck",
    duration: "8 weeks cohort",
    cost: "Free (selective)",
    skillGapsClosed: ["Networking", "Entrepreneurship", "Strategic Thinking"],
    whyItMatters: "Puts you in a room with ambitious founders, operators, and builders. The network alone can transform your career trajectory.",
    pathwayImprovement: "Accelerates Startup/Builder Path by connecting you with co-founders, mentors, and investors.",
    relevantPathways: ["startup-builder", "leadership"],
    difficulty: "intermediate",
  },
  {
    id: "rec-12",
    title: "Women in Tech Network",
    type: "community",
    provider: "Various local chapters",
    duration: "Ongoing",
    cost: "Free",
    skillGapsClosed: ["Networking", "Mentoring", "Leadership"],
    whyItMatters: "Access to mentorship circles, job boards, and speaking opportunities. Builds confidence and professional network in tech.",
    pathwayImprovement: "Supports all pathways through expanded professional network and peer learning.",
    relevantPathways: ["stable-growth", "leadership", "skill-pivot"],
    difficulty: "beginner",
  },
  {
    id: "rec-13",
    title: "Climate Tech Community (MCJ Collective)",
    type: "community",
    provider: "MCJ Collective",
    duration: "Ongoing",
    cost: "Free",
    skillGapsClosed: ["Climate Knowledge", "Networking", "Impact Measurement"],
    whyItMatters: "The largest climate tech community globally. Access to job opportunities, events, and thought leadership in the climate space.",
    pathwayImprovement: "Essential for Skill Pivot Path into climate tech. Connects you with hiring companies and domain experts.",
    relevantPathways: ["skill-pivot", "startup-builder"],
    difficulty: "beginner",
  },

  // ── Hackathons & Internships ──
  {
    id: "rec-14",
    title: "MLH Global Hack Week",
    type: "hackathon",
    provider: "Major League Hacking",
    duration: "1 week",
    cost: "Free",
    skillGapsClosed: ["Full-Stack Development", "Team Collaboration", "Rapid Prototyping"],
    whyItMatters: "Build something real in a week with a global community. Great resume addition and networking opportunity with sponsors.",
    pathwayImprovement: "Supports Startup/Builder Path by practicing rapid product development and teamwork.",
    relevantPathways: ["startup-builder", "skill-pivot"],
    difficulty: "beginner",
  },
  {
    id: "rec-15",
    title: "Google Summer of Code",
    type: "internship",
    provider: "Google",
    duration: "12 weeks (summer)",
    cost: "Paid stipend",
    skillGapsClosed: ["Open Source Development", "Software Engineering", "Code Review"],
    whyItMatters: "Work on real open-source projects mentored by experienced developers. Adds significant credibility to your engineering profile.",
    pathwayImprovement: "Boosts Stable Growth and High Salary paths with Google-affiliated open source experience.",
    relevantPathways: ["stable-growth", "high-salary"],
    difficulty: "intermediate",
  },
  {
    id: "rec-16",
    title: "Sustainability Innovation Challenge",
    type: "hackathon",
    provider: "EY & UN Environment",
    duration: "2-3 months",
    cost: "Free",
    skillGapsClosed: ["Impact Measurement", "Strategic Thinking", "Presentation Skills"],
    whyItMatters: "High-visibility competition with corporate sponsors. Winners get mentorship and potential job offers from sustainability-focused organizations.",
    pathwayImprovement: "Accelerates Skill Pivot Path into climate/sustainability by building domain credibility and industry connections.",
    relevantPathways: ["skill-pivot", "leadership"],
    difficulty: "intermediate",
  },
  {
    id: "rec-17",
    title: "Design Sprint Masterclass",
    type: "course",
    provider: "Google via Udemy",
    duration: "2 weeks",
    cost: "Free",
    url: "https://www.udemy.com/course/design-sprint/",
    skillGapsClosed: ["Design Thinking", "User Research", "Product Thinking"],
    whyItMatters: "Learn the 5-day design sprint methodology used at Google Ventures. Valuable for anyone in product, design, or consulting.",
    pathwayImprovement: "Supports Skill Pivot and Leadership paths by adding structured problem-solving methodology.",
    relevantPathways: ["skill-pivot", "leadership", "stable-growth"],
    difficulty: "beginner",
  },
  {
    id: "rec-18",
    title: "Advanced SQL for Data Analysis",
    type: "course",
    provider: "DataCamp",
    duration: "4 weeks",
    cost: "$25/mo",
    url: "https://www.datacamp.com/courses/advanced-sql",
    skillGapsClosed: ["Advanced SQL", "Data Pipeline Design", "Statistical Analysis"],
    whyItMatters: "SQL is the most universally required skill in data roles. Advanced SQL knowledge sets you apart from other junior candidates.",
    pathwayImprovement: "Strengthens Stable Growth Path by closing one of the most common and critical skill gaps in analytics roles.",
    relevantPathways: ["stable-growth", "high-salary"],
    difficulty: "intermediate",
  },
];
